### ISSUE TITLE
An error was encountered during analyses

### ISSUE THREAD

**Issue by liuxiong714** [chadlaing/Panseq#11]
Hi!

I was using Panseq to analysis a  group of genomes, but I have a problem as below:

An error was encountered during analyses.
If you uploaded your own data, please ensure it is fasta formatted, and if more than one genome is present in a file, please ensure that the fasta headers follow the format in the FAQ. Please try your analyses again, and if you continue to experience problems, send an email to chad.laing at the canada.ca domain. Thank you for using Panseq.

I have several singular files like this:
>lcl|s201|seqone
agcaaccaatctaatcacaagtaactgtttttcaacaagtttctatctgcatcaccgccg
atggatgtgcattatagaccatctcattccctttgcaaggggtatttatccctttttcac
ttgagtgccgtttttttctactattttgcgaaaa...............

>lcl|s202|seqone
agcaaccaatctaatcacaagtaactgtttttcaacaagtttctatctgcatcaccgccg
atggatgtgcattatagaccatctcattccctttgcaaggggtatttatccctttttcac
ttgagtgccgtttttttctactattttgcgaaaa.......................

>lcl|s203|seqone
agcaaccaatctaatcacaagtaactgtttttcaacaagtttctatctgcatcaccgccg
atggatgtgcattatagaccatctcattccctttgcaaggggtatttatccctttttcac
ttgagtgccgtttttttctactattttgcgaaaaaagtgata...................

Is there any wrong with my file format? I can't find it

thanks very much!

**Comment by chadlaing** [comment]
Hi,

Provided that the headers are really '>lcl|s201|seqone' then there shouldn't be an issue with the format.
Let me know if you are still experiencing problems, and I will run a test on the server.

Thanks,
Chad
