### ISSUE TITLE
problem with installing Panseq

### ISSUE THREAD

**Issue by camillaln** [chadlaing/Panseq#12]
Heia,
I am trying to install Panseq on my mac. 

When I run perl Build.pl I end up with this:
Checking prerequisites...
  requires:
    !  Bio::DB::Fasta is not installed
    !  Bio::Seq is not installed
    !  Bio::SeqIO is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Run 'Build installdeps' to install missing prerequisites.

Could not get valid metadata. Error is: ERROR: Missing required field 'dist_version' for metafile

Could not create MYMETA files
Creating new 'Build' script for 'Panseq' version ''

I then run 
./Build installdeps

But it does install those missing ones. Could you tell me how I can get those modules?

Thanks for any help with this,

Camilla

**Comment by chadlaing** [comment]
Hi,

Those are all BioPerl dependencies. If the build script doesn't install them, you could try installing BioPerl separately, and then running the Panseq tests to ensure everything is working.

Chad

**Comment by camillaln** [comment]
Thanks! I will try that :)

Sendt fra min iPhone
