### ISSUE TITLE
Get Muscle alignment fasta files from pangenome fragments

### ISSUE THREAD

**Issue by LuziaThea** [chadlaing/Panseq#27]
Dear Chad,

thank you so much for your great tool! 
I have a question concerning the Muscle alignment that is made for the fragments that are present in more genomes than the specified min. threshold.
I would like to use the Muscle alignment output files of the fragments for further analysis, specifically I would like to view the alignment in an alignment viewer like IGV or Jalview and then color the loci identified by the loci selector to see in what regions they are located. I would like to use this information to design suitable amplicons for further analysis.
However, I could not figure out how to get the Muscle alignment from Panseq. Is it possible to directly get it from the Panseq output or do I have to do the Muscle alignment separately myself using the locus_alleles.txt fasta files?

I am using Panseq with perl-5.31.2, muscle 3.8.31, ncbi-blast-2.9.0+ and MUMmer 3.23.

I thank you very much for your help in advance and I am looking forward to using your tool for my research!

Best regards,
Luzia

**Comment by chadlaing** [comment]
Hi @LuziaThea,

You should be able to get close to what you are after by setting `storeAlleles` to `1` in the configuration file, which will save the alleles in a `locus_alleles.txt` file. This is not the alignment, but is as close to one as is currently possible of outputting.

Thanks,
Chad
