### ISSUE TITLE
Core genome size and alignment

### ISSUE THREAD

**Issue by moorembioinfo** [chadlaing/Panseq#6]
Hi Chad, 

The snp.phylip file contains variant sites of all 'core' fragments, is it possible to extract the full alignment of fragments as a multifasta file per genome?

Thanks in advance for any comments on this!

**Comment by chadlaing** [comment]
Hi,

If you specify `locusAlleles    1` in the config file, an output file named `locus_alleles.fasta` will be produced. This contains a per-locus output of all "core" fragments from each genome (if they exist) for each pan-genome fragment. A per-genome alignment file of all the core regions could be produced, but at this time is not.

-Chad

**Comment by moorembioinfo** [comment]
Thanks!
