### ISSUE TITLE
Problems when installing Test::Pretty dependency

### ISSUE THREAD

**Issue by jpflorido** [chadlaing/Panseq#8]
Hi,
I'm trying to install Panseq and all its dependencies. All of them went OK, but Test:Pretty dependency:

You have loaded versions of test modules known to have problems with Test2.
# This could explain some test failures.
#  * Module 'Test::Pretty' is known to be broken in version 0.32 and below, newer versions have not been tested. You have: 0.32
...
Files=20, Tests=55,  3 wallclock secs ( 0.14 usr  0.03 sys +  2.50 cusr  0.32 csys =  2.99 CPU)
Result: FAIL
Failed 11/20 test programs. 24/55 subtests failed.
  TOKUHIROM/Test-Pretty-0.32.tar.gz
  ./Build test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports TOKUHIROM/Test-Pretty-0.32.tar.gz
Running Build install
  make test had returned bad status, won't install without force

I know that the problem is not Panseq itself, but without this dependency, cannot go forward. Any suggestions?
Thanks

**Comment by chadlaing** [comment]
What version of Perl?

**Comment by jpflorido** [comment]
5.18.2-2ubuntu1.1

**Comment by gsong1205** [comment]
I have the same problem. Do you know how to solve it?

**Comment by gsong1205** [comment]
When I am testing the panseq: perl t/output.t
Error message is: 
          You have loaded versions of test modules known to have problems with Test2.
          This could explain some test failures.
           * Module 'Test::Pretty' is known to be broken in version 0.32 and below, newer versions have not been tested. You have: 0.28

**Comment by chadlaing** [comment]
I am looking into this, it seems to be Test2 that is the issue.

**Comment by chadlaing** [comment]
I have updated the tests to use Test2::Bundle::Extended, instead of Test::Pretty.
Additionally, this update resolves the failing test issues (Issue #9) when using BLAST v2.3.0 or v2.4.0.
